### ISSUE TITLE
SONIC Corrupting ONIE on delta and Edgecore switches.

### ISSUE THREAD

**Issue by kamalkrbh** [Azure/SONiC#161]
Hello,
I tried installing SONIC images on Delta-AG9032V1 and Edgecore-5712 but it end up giving attached error and on next reboot it takes to grub console and It looks ONIE is currpted I need to reinstall ONIE.

I tried installing SONIC from (I Downloaded respective images on 13 March 2018):
https://github.com/Azure/SONiC/wiki/Supported-Devices-and-Platforms 

For :
Delta | AG9032V1 | Broadcom | Tomahawk | 32x100G
and
Edgecore | AS5712-54X | Broadcom | Trident2 | 72x10G
![capture](https://user-images.githubusercontent.com/23102241/37592076-e643a256-2b6d-11e8-8273-a99e480a687f.PNG)

**Comment by pollyhsu2git** [comment]
@STORDIS,
1). We just tested installing the SONIC Edgecore-5712 image (Built 2018-03-19 at
https://github.com/Azure/SONiC/wiki/Supported-Devices-and-Platforms), and it succeeded.  
2). For detailed test log, please refer to the attached ZIP file.
3). We did notice that there are ONIE installer script revisions (https://github.com/Azure/sonic-buildimage/pull/1468, and https://github.com/Azure/sonic-buildimage/pull/1512) these couple of days~
[SONiC-AS5712_54X-j_n527-56efb41-PORT_MAP_OK-20180320_1106.zip](https://github.com/Azure/SONiC/files/1827865/SONiC-AS5712_54X-j_n527-56efb41-PORT_MAP_OK-20180320_1106.zip)

**Comment by pichuang** [comment]
Hi @STORDIS 

This is Phil Huang from Edgecore Networks <phil_huang@edge-core.com>

I have tested the issue and download latest BRCM SONiC binary code today.

The root cause is **mount over existing directory "/mnt/onie-boot"**

Please check my processes as below
```
ONIE:/mnt # ls
onie-boot
ONIE:/mnt # mkdir usb
ONIE:/mnt # mount /dev/sdb1 /mnt/usb/
ONIE:/mnt # cd usb/
ONIE:/mnt/usb # ls
sonic-broadcom.bin
ONIE:/mnt/usb # md5sum sonic-broadcom.bin
b8e7c578c50acd5b22053a959b1623f2  sonic-broadcom.bin
ONIE:/mnt/usb # sha256sum sonic-broadcom.bin
395fa325e7ba865c55fb60a430cc8c3493b73c1d16c53e7b74bfeda8720bcdd5  sonic-broadcom.bin
ONIE:/mnt/usb # onie-nos-install sonic-broadcom.bin
```
<img width="1280" alt="screen shot 2018-03-20 at 12 18 19" src="https://user-images.githubusercontent.com/5253671/37635948-cc849bdc-2c39-11e8-9c75-b651a3f4a72b.png">

And you can get fresh SONiC environment on AS5712-54X

<img width="776" alt="screen shot 2018-03-20 at 12 24 31" src="https://user-images.githubusercontent.com/5253671/37635937-bbc40300-2c39-11e8-9854-2b662bbf38cf.png">
