### ISSUE TITLE
I install SONiC ONIE Image on my supermicro SSE-G3648B and get some error

### ISSUE THREAD

**Issue by wjf1993** [Azure/SONiC#174]
hello everyone.I follow the steps of the document to install(https://github.com/Azure/SONiC/wiki/Quick-Start) and I finished installing the NOS.But i don't why i can only “welcome grub”.so How should I go back to the ONIE environment？

**Comment by edrozenberg** [comment]
Posting this here in case anyone else wonders. Yes, it's impossible to use any of the available SONiC images on these switches. The old SONiC images bork ONIE/Grub, the newer ones fail to install with "Out of Memory". I will try building my own smaller SONiC image, and if even that fails, it's time to toss/resell these SMC switches. You can also put Super Micro's own SMIS software on them, but it costs ~ $350 per license (license product code SFT-SMCPL1G).

Super Micro ONIE restore guide:
https://www.supermicro.com/support/faqs/faq.cfm?faq=32384

I used the attached recovery image - unzip and dd'it to a flash drive as the FAQ describes. I built my own ONIE update/restore images. This is ONIE version 2020.05br (the latest one supported on these switches):

[onie-recovery-x86_64-cel_e1031-r0.iso.gz](https://github.com/sonic-net/SONiC/files/9426230/onie-recovery-x86_64-cel_e1031-r0.iso.gz)

Some other info -

EdgeCore ONIE recovery:
https://support.edge-core.com/hc/en-us/articles/360021708534--ONIE-How-to-recover-ONIE-on-Edgecore-x86-platform-switch-via-USB-

Dell ONIE recovery:
https://infohub.delltechnologies.com/static/media/client/7phukh/57ae5efd-8700-40e4-a268-37a88b6763fc.pdf

**Comment by mariusleu** [comment]
In my case the screen was stuck into "Welcome to GRUB" because of wrong baud rate used on the serial console.

As per the [docs](https://github.com/sonic-net/SONiC/wiki/Quick-Start), the default baud rate in SONiC is 9600.

Using `screen /dev/ttyUSB0 9600` worked for me after installing the [SONiC 201811 (broadcom)](https://sonic-build.azurewebsites.net/api/sonic/artifacts?branchName=201811&platform=broadcom&target=target%2Fsonic-broadcom.bin)
