### ISSUE TITLE
  When MGMT VRF is deleted, I cannot Ping through eth0 port through console

### ISSUE THREAD

**Issue by yutian-mtk** [Azure/SONiC#551]
When I use config db.json or config command to configure MGMT VRF, it can isolate eth0. After I use config mvrf del MGMT to delete MGMT VRF, eth0 port should be released to global. However, when I log in the device with console port and Ping the IP of eth0 port directly, I cannot Ping the communication.
    I want to know how sonic deals with the deletion of MGMT VRF and whether the eth0 port is in the same state as it was before MGMT VRF was added. What's the reason why I can't Ping eth0 port after deleting MGMT VRF
thanks！

**Comment by yutian-mtk** [comment]
[version]
SONiC Software Version: SONiC.nephos-201911-558292f-201912120118.0-dirty-20191212.204239
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: da6fde5c
Build date: Fri Dec 13 04:57:37 UTC 2019
Built by: build@nps65

**Comment by kannankvs** [comment]
1.	Issue is not specific to management VRF. Issue is observed even with data vrf as follows. 
a.	By default, when SONiC is rebooted, following three ip rules are present.
root@sonic:~# ip rule show
1001:    from all lookup local 
32766:  from all lookup main 
32767:  from all lookup default 
b.	When any VRF (data VRF or management VRF)  is created, a new rule is getting added automatically by kernel as follows.
root@sonic:~# ip link add vrf-blue type vrf table 10
root@sonic:~# ip rule show
1000:    from all lookup [l3mdev-table] 
1001:    from all lookup local 
32766:  from all lookup main 
32767:  from all lookup default 
root@sonic:~#
c.	Now, if any IP address is configured and if we try to ping it, it does not work. Configuring the IP address is adding an IP rule for eth0’s IP address, which creates this issue. This rule should not be having higher priority than the rule “1001:from all lookup local “. Self originated packets with source IP as eth0 IP will end up in looking up the “default” table (it should actually lookup “local” table first) which will result in wrong routing and hence ping will fail.
root@sonic:~# config interface ip add eth0 100.104.47.74/24 100.104.47.254
root@sonic:~# ping 100.104.47.74
PING 100.104.47.74 (100.104.47.74) 56(84) bytes of data.
 
root@sonic:~# ip rule show
1000:    from all lookup [l3mdev-table] 
1000:    from 100.104.47.74 lookup default 
1001:    from all lookup local 
32766:  from all lookup main 
32767:  from all lookup default 
root@sonic:~#
 
2.	Root cause is due to the “eth0 ip rule” that is getting added from interfaces.j2 (this code exists from beginning) when IP address is configured for eth0.  The priority for this “eth0 rule” varies based on the already existing IP rules. When VRF was never created, this “eth0 rule” is getting added with priority 32765. This way, all self-originated packets will lookup into “local” routing table (rule priority is 1001) before looking up the “default” routing table (rule priority is 32767).  When VRF is created for very first time, kernel is adding a rule for “l3mdev” with priority as 1000 which is never getting deleted even when VRF is deleted. Once if any VRF is created,  the “eth0 rule” is getting added with priority 1000, which goes with higher priority than “1001:from all lookup local”, which results in ping failure. 
 
3.	**Possible Solutions: **  
a.  Option1: Remove the “eth0 ip rule” specific to interface IP address.
b.  Option2: Retain the “eth0 rule” remain, but add priority as “32765” (instead of not specifying the preference), so that the rule is always having lower priority than the rule “1001:from all lookup local”. 
c.  Option3: Lower the priority for "1001:    from all lookup local" to 0.

Raised a [PR4058](https://github.com/Azure/sonic-buildimage/pull/4058)  with Option2 to solve the same. 
@yutian-mtk : Comments are welcome.

**Comment by prsunny** [comment]
@yutian-mtk , can you please take the fix, validate and provide feedback?

**Comment by yutian-mtk** [comment]
@prsunny ,I've verified this fix,It's verified.The solution fits the option a.I tested two issues.
      1.As the title of this issue.
      2.When eth0 in vrf mgmt, given same ip to another interface such as Ethernet1, then it would not work - the neighbor attached to Ethernet1 would ping failed,This modification method also fixes this issue.
      Anyway, these two issues have been fixed.
